Enh/issue#1/s3 ec2
Apurv-TA/aws_assignment pull request #2
Opened 2022-04-20 06:34 UTC by Apurv-TA

For this project our goal was to study about AWS and deploy a flask application to EC2 instance.
Link to the flask application: 3.91.59.155:8085

2022-04-22 12:03 UTC, mukti-mrinalini commented
1. Update the README with the commands you are using(Similar to how you have added in the PR description)
2. Use correct tags(owner : <email id> and project: aws-training)
3. Remove the pycache files(Use .gitignore file)
4. Add the .service file
5. Update README with the local testing of the flask app

2022-04-22 18:47 UTC, Apurv-TA commented
@mukti-mrinalini I have updated the PR please review it.

2022-04-23 05:58 UTC, mukti-mrinalini requested changes
1. Edit the tags of the resources you created
(Just these two tags
owner:    apurv.master@tigeranalytics.com
project:  aws-training)
2. Change the same in the README and PR description

2022-04-23 09:41 UTC, Apurv-TA commented
@mukti-mrinalini please verify

2022-04-23 11:42 UTC, mukti-mrinalini approved these changes
Approved

2022-04-25 13:36 UTC, merged

2022-04-25 16:10 UTC, leninkumar-sv-tiger commented on deploy/conda/requirements.txt
> +botocore @ file:///opt/conda/conda-bld/botocore_1649076662316/work
Why are these files have @file notation ?

2022-04-25 16:11 UTC, leninkumar-sv-tiger commented on s3.py
> +    s3 = boto3.client('s3')
what is the difference between boto3.client and boto3.resource ?

2022-04-25 16:12 UTC, leninkumar-sv-tiger commented on s3.py
> +    s3 = boto3.resource("s3")
Is it possible to move these variables to global scope ?

2022-04-25 16:12 UTC, leninkumar-sv-tiger reviewed
Please look at the comments ?

2022-04-26 18:43 UTC, Apurv-TA commented on s3.py
> +    s3 = boto3.resource("s3")
Yes, It is. The reason I didn't do it is because I want to apply both boto3.client and boto3.resource in the code.
Should I move these to global scope?

2022-04-26 18:51 UTC, Apurv-TA commented on s3.py
> +    s3 = boto3.client('s3')
Client and Resource both are used by boto3 for API calls to an AWS service.

1. Client is the original boto3 API abstraction while resource is the newer one.
2. Client provides low-level AWS service access while resource provides high-level, object-oriented API.
3. As for functionality client seems to give access to all AWS service operations while resource doesn't.

2022-04-26 18:56 UTC, Apurv-TA commented on deploy/conda/requirements.txt
> +botocore @ file:///opt/conda/conda-bld/botocore_1649076662316/work
These packages with @file notation are direct reference to that package, It is used by some automated tools as an alternative to normal version specifier. In this case it seems to be file URLs.

2022-04-26 19:03 UTC, Apurv-TA commented on deploy/conda/requirements.txt
> +botocore @ file:///opt/conda/conda-bld/botocore_1649076662316/work
Should I have used conda environment file in place of requirements.txt file for deployment?